# Replication controllor make sure that the sepecified number of pods are running all the time.
# If extra pods are running, it will delete it.
# If fewer pods are running or a pod get error it will destroy it and create new.
# Replication controller is good for one pod too, because it will make sure that the pod is running.
# Replication controller knows which pod to help by getting the label of the pod.


# Replication controller is part of the initial stable release so its value is v1
apiVersion: v1
# Kind of object we are creating is ReplicationController
kind: ReplicationController
#
metadata:
  labels:
    name: cassandra
  # Name of the replication controller is cassandra-rc
  name: cassandra-rc
spec:
  # replicas property specify the number of pod instances that we are creating, in our case 1
  replicas: 1
  # selector select the pods with labels cassandra
  selector:
    name: cassandra-db
  # The template define the pod configuration. It is similar to pod manifest file.
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
        - image: miratepuffin/cassandralab:latest
          name: cassandra
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra-peers

            # Feel free to change the following:
            - name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: Kubernetes Cluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          ports:
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: data
      volumes:
        - name: data
          emptyDir: {}
